# Notes

In [1]:
# Import NumPy Library in Jupyter Notebook
import numpy as np

In [2]:
# Array Declaration
a = np.array([1,2,3], dtype='int16')

In [21]:
# Print Array
print(a)

[1 2 3]


In [3]:
# Declaring 2D Array and printing it
b = np.array([[1.2,4.5,6.7],[3.5,8.9,6.3]])
print(b)

[[1.2 4.5 6.7]
 [3.5 8.9 6.3]]


In [23]:
# Get dimension
a.ndim

1

In [6]:
b.ndim

2

In [24]:
# Get Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [25]:
# Get Data Type
a.dtype

dtype('int16')

In [10]:
b.dtype

dtype('float64')

In [26]:
# Get Item Size
a.itemsize

2

In [14]:
b.itemsize

8

In [27]:
# Get Size
a.size

3

In [17]:
b.size

6

In [28]:
# Get Total Size = Size * Item Size (In Bytes)
a.size * a.itemsize

6

In [19]:
b.size * b.itemsize

48

In [30]:
# Get Total Size (Method 2)
a.nbytes

6

In [31]:
b.nbytes

48

In [32]:
# Get specific element using [row, column]
b[1,2]

np.float64(6.3)

In [34]:
# Using Negative Notation Just Like Lists
b[1,-1]

np.float64(6.3)

In [35]:
# Get a specific row
b[0,:]

array([1.2, 4.5, 6.7])

In [36]:
# Get a specific column
b[:,1]

array([4.5, 8.9])

In [40]:
# Get a specific range of elements using [start_index: end_index: step_size]
b[0, 0:3:2]

array([1.2, 6.7])

In [41]:
# Change specific element
b[0,2] = 10.1

In [42]:
print(b)

[[ 1.2  4.5 10.1]
 [ 3.5  8.9  6.3]]


In [45]:
# Change 2 elements simultaneously
b[:, 1] = [3.4, 6.1]

In [46]:
print(b)

[[ 1.2  3.4 10.1]
 [ 3.5  6.1  6.3]]


In [47]:
b[1,:] = [1.2,2.3,3.4]

In [48]:
print(b)

[[ 1.2  3.4 10.1]
 [ 1.2  2.3  3.4]]


In [4]:
# 3D Array example
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [51]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [55]:
# Get specific element in 3D Array
c[1,0,1]

np.int64(8)

In [56]:
c[1,1,2] = 20

In [57]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 20]]]


In [63]:
# Get Specific Row
c[1,0,:]

array([7, 8, 9])

In [64]:
# Get Specific Column
c[:,:,1]

array([[ 2,  5],
       [ 8, 11]])

In [65]:
# Change a specific row/column
c[:,:,1] = [[9,9],[9,9]]

In [66]:
print(c)

[[[ 1  9  3]
  [ 4  9  6]]

 [[ 7  9  9]
  [10  9 20]]]


In [5]:
# All Zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [9]:
# All Ones Matrix
np.ones((2,2,1), dtype='int16')

array([[[1],
        [1]],

       [[1],
        [1]]], dtype=int16)

In [11]:
# Other than 1 and 0-based matrix
np.full((2,3), 67, dtype='float32')

array([[67., 67., 67.],
       [67., 67., 67.]], dtype=float32)

In [12]:
# Full Like matrix
np.full_like((a), 3)

array([3, 3, 3], dtype=int16)

In [15]:
# Doing the same but using full function
np.full((a.shape), 3)

array([3, 3, 3])

In [16]:
# Random decimal numbers in a matrix
np.random.rand(3,5)

array([[0.20886915, 0.62561237, 0.13881848, 0.39852082, 0.68531027],
       [0.39133506, 0.8649771 , 0.05165131, 0.26379598, 0.92523367],
       [0.27786012, 0.19485017, 0.39802556, 0.63051763, 0.39495836]])

In [23]:
# Random integer numbers in a matrix
np.random.randint(32, size=(2,4))

array([[ 1,  8, 25, 29],
       [22,  2, 20,  7]])

In [25]:
# Random integer numbers in a matrix in a range (Note - can also use negative values)
np.random.randint(20,25, size=(2,4))

array([[24, 20, 20, 22],
       [21, 22, 21, 22]])

In [29]:
# To create an identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
# Repeating previous arrays to create a new array by repeating each element simultaneously
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [34]:
repeat = np.repeat(arr, 3)

In [35]:
repeat

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10])

In [36]:
arr2 = np.array([[1,2,3,4,5,6]])

In [39]:
# Repeating the rows
repeat2 = np.repeat(arr2, 3, axis = 0)

In [40]:
print(repeat2)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [41]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
z[1,1] = 9

In [44]:
output[1:4,1:4] = z

In [45]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
# Copying one array to other
copy = np.copy(arr)

In [47]:
copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
copy[3] = 111

In [49]:
copy

array([  1,   2,   3, 111,   5,   6,   7,   8,   9,  10])

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Math Capabilities of an array in NumPy
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [57]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
arr * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [59]:
arr / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ])

In [60]:
arr % 3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1])

In [63]:
# Sum of matrices
a + b

array([[ 2.2,  6.5,  9.7],
       [ 4.5, 10.9,  9.3]])

In [64]:
a + b + c

array([[[ 3.2,  8.5, 12.7],
        [ 8.5, 15.9, 15.3]],

       [[ 9.2, 14.5, 18.7],
        [14.5, 21.9, 21.3]]])

In [65]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [69]:
# Take the sine, cosine and other trigonometric funcitons of all the elements in an array
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [70]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [71]:
d = np.ones((2,3))

In [72]:
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
e = np.full((3,2), 2)

In [74]:
e

array([[2, 2],
       [2, 2],
       [2, 2]])

In [76]:
a * b

array([[ 1.2,  9. , 20.1],
       [ 3.5, 17.8, 18.9]])

In [80]:
# For Matrix Multiplication (Linear Algebra)
np.matmul(d,e)

array([[6., 6.],
       [6., 6.]])

In [81]:
matrix = np.identity(2)

In [82]:
matrix

array([[1., 0.],
       [0., 1.]])

In [83]:
np.linalg.det(matrix)

np.float64(1.0)

In [85]:
# Statistics
stats = np.array([[1,2,3],[4,5,7]])
print(stats)

[[1 2 3]
 [4 5 7]]


In [89]:
# Finding min and max
np.max(stats)

np.int64(7)

In [90]:
np.min(stats)

np.int64(1)

In [91]:
# Finding the min and max on the axis = 1
np.max(stats, axis=1)

array([3, 7])

In [92]:
np.min(stats, axis=1)

array([1, 4])

In [93]:
np.sum(stats, axis=1)

array([ 6, 16])

In [2]:
# Reorganizing An Array
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
v1

array([1, 2, 3, 4])

In [6]:
v2

array([5, 6, 7, 8])

In [8]:
# Horizontally Stacking Vectors
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
# Load Data From File
filedata = np.genfromtxt('data.txt', delimiter=',')

In [17]:
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [22]:
# Changing the data type of the file
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [24]:
# Get boolean values for certain condition on data inside the file
filedata > 30

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [25]:
# Get the data satisfying the condition
filedata[filedata > 30]

array([196,  75,  34,  42,  33, 766,  75,  55,  33, 999,  78,  76,  88],
      dtype=int32)

In [26]:
# We can index with a list
array = np.array([1,2,3,4,5,6,10,7,8,9])
print(array)

[ 1  2  3  4  5  6 10  7  8  9]


In [27]:
array[[2,4,6]]

array([ 3,  5, 10])

In [30]:
# Check column-wise if any value > 50
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
# Check column-wise if all values > 50
np.all(filedata > 50, axis=0)

In [33]:
# Check values to satisfy a range
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [38]:
# Indexing
mat = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [39]:
mat[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [40]:
mat[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [41]:
mat[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

# Let's Practice

In [1]:
import numpy as np

In [2]:
# Creating an numpy array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Using ndarray.ndim -> The number of axes (dimensions) of the array
print(arr.ndim)

2


In [4]:
# Using ndarray.shape -> The size of the array in each dimension
print(arr.shape)

(3, 3)


In [5]:
# Using ndarray.size -> The total number of elements in the array
print(arr.size)

9


In [6]:
# Using ndarray.dtype -> The data type of the elements inside the array
print(arr.dtype)

int64


In [7]:
# Change data type of the array
arr.dtype = 'int32'

In [13]:
print(arr.dtype)

int32


In [14]:
# Using ndarray.itemsize -> The size in bytes of each element of the array
print(arr.itemsize)

4


In [10]:
# Using ndarray.data -> The buffer containing the actual elements of the array (Not much used)
print(arr.data)

In [18]:
arr

array([[1, 0, 2, 0, 3, 0],
       [4, 0, 5, 0, 6, 0],
       [7, 0, 8, 0, 9, 0]], dtype=int32)

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Getting the total size of array in bytes = size of array * size of each element in bytes
print(arr.size * arr.itemsize)

72


In [23]:
arr.itemsize

8

In [24]:
# Changing the data type of an array explicitly at the time of creation
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='complex')
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [45]:
# Note - array method transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.

In [27]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b.shape)

(3, 3)


In [28]:
# Using ndarray.zeros((n,m)) -> Creates an array with all elements 0s of dimensions (m,n)
c = np.zeros((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# Using ndarray.ones((n,m)) -> Creates an array with all elements 1s of dimensions (m,n)
d = np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
# Using ndarray.empty((n,m)) -> Creates an array with random valued elements of dimensions (m,n)
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [43]:
# Using np.arange(start, end (excluded), stepsize) -> To create sequences of numbers
np.arange(10,45,5)

array([10, 15, 20, 25, 30, 35, 40])

In [44]:
# Note - np.arange() is not recommended in case of float values due to number restrictions
# Thus we use np.linspace(start, end(excluded), total_elements_needed)

In [46]:
np.linspace(10,50,8)

array([10.        , 15.71428571, 21.42857143, 27.14285714, 32.85714286,
       38.57142857, 44.28571429, 50.        ])

In [10]:
# Using reshape((m,n)) -> Reshapes an existing array into (m,n) array
arr = np.arange(1000).reshape((10,100))

In [12]:
# Note - If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners
# To disable this behaviour and force NumPy to print the entire array -> (a) import sys module
# (b) np.set_printoptions(threshold=sys.maxsize)

In [13]:
# Matrix Operations
a = np.array([[1,2,3],[5,6,7],[9,8,4]])

In [14]:
b = np.array([[2,5,1],[4,8,6],[3,9,7]])

In [15]:
print(a)
print(b)

[[1 2 3]
 [5 6 7]
 [9 8 4]]
[[2 5 1]
 [4 8 6]
 [3 9 7]]


In [17]:
# Arithmetic Operations on a single matrix
print(a + 2)

[[ 3  4  5]
 [ 7  8  9]
 [11 10  6]]


In [18]:
print(a-3)

[[-2 -1  0]
 [ 2  3  4]
 [ 6  5  1]]


In [19]:
print(b*3)

[[ 6 15  3]
 [12 24 18]
 [ 9 27 21]]


In [20]:
print(b/5)

[[0.4 1.  0.2]
 [0.8 1.6 1.2]
 [0.6 1.8 1.4]]


In [21]:
print(a**2)

[[ 1  4  9]
 [25 36 49]
 [81 64 16]]


In [22]:
print(b%4)

[[2 1 1]
 [0 0 2]
 [3 1 3]]


In [23]:
# Arithmetic Operations on 2 matrices
print(a+b)

[[ 3  7  4]
 [ 9 14 13]
 [12 17 11]]


In [24]:
print(a-b)

[[-1 -3  2]
 [ 1 -2  1]
 [ 6 -1 -3]]


In [26]:
# Matrix elementwise product just like add and subtract
print(a*b)

[[ 2 10  3]
 [20 48 42]
 [27 72 28]]


In [28]:
# Matrix elementwise division just like add, subtract and multiply
print(a/b)

[[0.5        0.4        3.        ]
 [1.25       0.75       1.16666667]
 [3.         0.88888889 0.57142857]]


In [30]:
# Matrix multiplication (not elementwise) - Method 1
print(a @ b)

[[ 19  48  34]
 [ 55 136  90]
 [ 62 145  85]]


In [69]:
# Matrix multiplication (not elementwise) - Method 2
print(a.dot(b))

[[ 30.  36.  42.]
 [ 78.  96. 114.]
 [ 69.  90. 111.]]


In [33]:
a *= 2

In [34]:
a

array([[ 2,  4,  6],
       [10, 12, 14],
       [18, 16,  8]])

In [35]:
b -= 2

In [36]:
b

array([[ 0,  3, -1],
       [ 2,  6,  4],
       [ 1,  7,  5]])

In [37]:
b += a

In [38]:
b

array([[ 2,  7,  5],
       [12, 18, 18],
       [19, 23, 13]])

In [40]:
b %= 2

In [41]:
b

array([[0, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [43]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float64')
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [44]:
b /= 2

In [45]:
b

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [60]:
# Using random((m,n)) -> Creates an array of size (m,n) having random values
rg = np.random.default_rng(3)
array = rg.random((4,3))

In [61]:
array

array([[0.08564917, 0.23681051, 0.80127447],
       [0.58216204, 0.09412864, 0.43312694],
       [0.4790513 , 0.15973891, 0.73457715],
       [0.11367202, 0.39122819, 0.51674018]])

In [62]:
# Universal Functions
A = np.array([[2,3,4],[1,6,5],[9,7,8]])

In [63]:
B = np.array([[10,16,17],[4,7,2],[18,9,11]])

In [64]:
np.sin(A)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [ 0.84147098, -0.2794155 , -0.95892427],
       [ 0.41211849,  0.6569866 ,  0.98935825]])

In [65]:
np.cos(B)

array([[-0.83907153, -0.95765948, -0.27516334],
       [-0.65364362,  0.75390225, -0.41614684],
       [ 0.66031671, -0.91113026,  0.0044257 ]])

In [66]:
np.sqrt(A)

array([[1.41421356, 1.73205081, 2.        ],
       [1.        , 2.44948974, 2.23606798],
       [3.        , 2.64575131, 2.82842712]])

In [67]:
np.exp(B)

array([[2.20264658e+04, 8.88611052e+06, 2.41549528e+07],
       [5.45981500e+01, 1.09663316e+03, 7.38905610e+00],
       [6.56599691e+07, 8.10308393e+03, 5.98741417e+04]])

In [68]:
np.add(A,B)

array([[12, 19, 21],
       [ 5, 13,  7],
       [27, 16, 19]])

In [70]:
np.min(A)

np.int64(1)

In [71]:
np.max(B)

np.int64(18)

In [73]:
# Sorting every row
np.sort(B)

array([[10, 16, 17],
       [ 2,  4,  7],
       [ 9, 11, 18]])

In [74]:
np.mean(A)

np.float64(5.0)

In [75]:
np.median(B)

np.float64(10.0)

In [2]:
arr = np.array([[1,2,3],[4,5,7],[6,8,9]])

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])**2

In [4]:
print(a)

[  1   4   9  16  25  36  49  64  81 100]


In [16]:
# Printing the list
for i in a:
    print(i)

1000
4
1000
16
1000
36
49
64
81
100


In [14]:
# Get a element of a list
print(a[3])

16


In [13]:
# Get a range of elements
print(a[0:4])

[1000    4 1000   16]


In [11]:
# Changing every 2nd element to 1000 from index 0 to 6 excluding 6
# Can also be done using in case of start index as 0 -> a[:6:2] = 1000
a[0:6:2] = 1000

In [9]:
print(a)

[1000    4 1000   16 1000   36   49   64   81  100]


In [12]:
# Reverse of a list
print(a[::-1])

[ 100   81   64   49   36 1000   16 1000    4 1000]


In [17]:
# Get an element in a multidimensional array
print(arr[1,2])

7


In [18]:
# We can assign the value to an index in an array
arr[1,2] = 11

In [19]:
print(arr)

[[ 1  2  3]
 [ 4  5 11]
 [ 6  8  9]]


In [23]:
# Getting a column
print(arr[:,1])

[2 5 8]


In [24]:
# Get column elements for specific rows
print(arr[0:2,2])

[ 3 11]


In [26]:
# Get a row
print(arr[1,:])

[ 4  5 11]


In [27]:
# Get rows for specific columns
print(arr[2,1:3])

[8 9]


In [28]:
# Get using negative index (Reverse indexing)
print(arr[-1])

[6 8 9]


In [29]:
# Iterating every row in a 2D array
for row in arr:
    print(row)

[1 2 3]
[ 4  5 11]
[6 8 9]


In [30]:
# Iterating each element in a 2D array
for element in arr.flat:
    print(element)

1
2
3
4
5
11
6
8
9


In [33]:
# Here arr.flat makes the 2D array into a 1D array without permanently changing the array (Only used in case of iterations)

In [34]:
print(arr)

[[ 1  2  3]
 [ 4  5 11]
 [ 6  8  9]]


In [35]:
# We can do the iterations, indexing etc in 3D arrays by using the similar approach

In [37]:
# Shape manipulation
print(arr.shape)

(3, 3)


In [42]:
# Makes n dimensional array into 1D array
print(arr.ravel())

[ 1  2  3  4  5 11  6  8  9]


In [44]:
# Reshaping the shape of array keeping in mind the number of elements in it
arr.reshape((9,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [11],
       [ 6],
       [ 8],
       [ 9]])

In [45]:
print(arr)

[[ 1  2  3]
 [ 4  5 11]
 [ 6  8  9]]


In [47]:
# To get the transpose of the array
print(arr.T)

[[ 1  4  6]
 [ 2  5  8]
 [ 3 11  9]]


In [49]:
# If we need to change the shape of array permanently -> arr.resize((m,n))
arr.resize((1,9))

In [50]:
print(arr)

[[ 1  2  3  4  5 11  6  8  9]]


In [53]:
arr2 = np.array([7,3,7,9,5,2,8,5,10])

In [54]:
print(arr2)

[ 7  3  7  9  5  2  8  5 10]


In [58]:
# Vertically stacking the arrays
print(np.vstack((arr, arr2)))

[[ 1  2  3  4  5 11  6  8  9]
 [ 7  3  7  9  5  2  8  5 10]]


In [60]:
print(arr)

[[ 1  2  3  4  5 11  6  8  9]]


In [62]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])

In [67]:
# Horizontally stacking the arrays (1D)
print(np.hstack((arr3, arr2)))

[ 1  2  3  4  5  6  7  8  9  7  3  7  9  5  2  8  5 10]


In [68]:
arr4 = np.array([[1,2,3,4,5,6,7,8,9]])

In [69]:
# Horizontally stacking the arrays (2D)
np.column_stack((arr, arr4))

array([[ 1,  2,  3,  4,  5, 11,  6,  8,  9,  1,  2,  3,  4,  5,  6,  7,
         8,  9]])

In [70]:
a = np.array([[1, 2], [3, 4]])

In [71]:
b = np.array([[5, 6]])

In [78]:
# Concatenate 2 arrays on the basis of axis (Here axis = 0 means vertically)
# Here number of rows must be same
print(np.concatenate((a, b), axis=0)) 

[[1 2]
 [3 4]
 [5 6]]


In [79]:
# Concatenate 2 arrays on the basis of axis (Here axis = 1 means horizontally)
# Here number of rows must be same
print(np.concatenate((a,b.T),axis=1))

[[1 2 5]
 [3 4 6]]


In [81]:
print(arr)

[[ 1  2  3  4  5 11  6  8  9]]


In [87]:
# Using np.hsplit(array_name, number) to split array into number of arrays horizontally
print(np.hsplit(arr,3))

[array([[1, 2, 3]]), array([[ 4,  5, 11]]), array([[6, 8, 9]])]


In [88]:
# Specifying from where to split
print(np.hsplit(arr,(3,5)))

[array([[1, 2, 3]]), array([[4, 5]]), array([[11,  6,  8,  9]])]


In [89]:
print(np.hsplit(arr,(2,6)))

[array([[1, 2]]), array([[ 3,  4,  5, 11]]), array([[6, 8, 9]])]


In [96]:
# Using np.vsplit(array_name, number) to split array into number of arrays vertically
x = np.arange(16.0).reshape(4, 4)
print(x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [97]:
print(np.vsplit(x, 2))

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [111]:
# Note - We can also use np.split() for doing the same things above but by providing the axis
c = np.arange(9)

In [112]:
print(c)

[0 1 2 3 4 5 6 7 8]


In [114]:
np.split(c, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [118]:
c.reshape((9,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [119]:
np.split(c, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Creating a shallow copy of an array
c = arr.view()

In [6]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# c is not equal to arr
c is arr

False

In [18]:
# c is the view of an array named arr
c.base is arr

True

In [19]:
# Does it have it's own data
c.flags.owndata

False

In [20]:
# Changing the shape of c doesn't change the shape of arr
c = c.reshape((9,1))

In [12]:
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [13]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Alteration of elements in c changes it in arr
c[0,0] = 10

In [15]:
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [22]:
# Creating deep copy of the arr
d = arr.copy()

In [23]:
print(d)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [25]:
# d is not equal to arr
d is arr

False

In [26]:
# d doesn't share anything with arr
d.base is arr

False

In [27]:
# Alteration of elements of d aren't reflected in arr
d[0,0] = 999
print(d)

[[999   2   3]
 [  4   5   6]
 [  7   8   9]]


In [28]:
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [29]:
# Indexing with array of indices
a = np.arange(12)**3
print(a)

[   0    1    8   27   64  125  216  343  512  729 1000 1331]


In [30]:
# Array of indices
i = np.array([0, 5, 2, 9, 4])
print(i)

[0 5 2 9 4]


In [32]:
# Indexing with array of indices
print(a[i])

[  0 125   8 729  64]


In [33]:
# Using 2D Array for the same thing
j = np.array([[5, 1], [10, 4]])
print(j)

[[ 5  1]
 [10  4]]


In [34]:
print(a[j])

[[ 125    1]
 [1000   64]]


In [35]:
a = np.arange(12).reshape(3, 4)

In [36]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
i = np.array([[0, 1],[1, 2]])

In [39]:
j = np.array([[2, 1],[3, 3]])

In [40]:
# Using a tuple of indices to index an array
l = (i,j)

In [41]:
print(a[l])

[[ 2  5]
 [ 7 11]]


In [42]:
# The End of Practicing the basics